import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from './Head'
import Header from './Components/Header/Header'
// import 'bootstrap/dist/css/bootstrap.min.css';


import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head/>
      <body className={inter.className}>
        <Header/>
        {children}</body>
    </html>
  );
}
