import React from 'react'

const Head = () => {
  return (
    <React.Fragment>
      <title>VYB Store</title>
      <meta content='width=device-width initial-scale=1' name='viewport'/>
      <meta name='description' content='Generated by create next app'/>
      <link rel='icon' href='/favicon.ico'/>
    </React.Fragment>
  )
}

export default Head